### ISSUE TITLE
Increase gzip compression level

### ISSUE THREAD

**Issue by niutech** [jquery/codeorigin.jquery.com#38]
I have tested the latest jQuery version at code.jquery.com using [Gzip and Brotli Compression Level Estimator](https://tools.paulcalvano.com/compression.php) and there is room for improvement:

![jquery test](https://user-images.githubusercontent.com/384997/43431792-075e1442-9470-11e8-8fb3-dd586b47a625.png)

Please increase the gzip compression level from 1 to at least 6 and enable brotli compression method. Thanks.

**Comment by Krinkle** [comment]
I have checked in the Highwinds StrikeTracker, which is configuration panel for the StackPath CDN service we use on code.jquery.org, and there is indeed an optoin to tune the Gzip compression level.

However, according to the settings there these are already set at the highest. The system they use ranges from 0-6 (rather than 1-9) where 0 is faster without compression and 6 is the highest compression, which is the setting we already use for code.jquery.com.

| CDN: code.jquery.org / Compression
|--
| <img width="600" alt="capture" src="https://user-images.githubusercontent.com/156867/87490122-c1347780-c63c-11ea-8186-c107b883d685.png">

**Comment by XhmikosR** [comment]
At some point in the past, I had requested StackPath for this change so maybe it was applied back then. There's nothing more you can do, since last time I checked, they didn't offer Brotli compression.
