### ISSUE TITLE
301 Redirect Loop due to unknown CDN nodes (*-latest files)

### ISSUE THREAD

**Issue by muylomas** [jquery/codeorigin.jquery.com#68]
The url https://code.jquery.com/jquery-latest.min.js isn't working due to a redirect loop.

I'm trying to reach the url from Uruguay, South America. Any browser is giving the next problem:
This page isn’t working
code.jquery.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

**Comment by mgol** [comment]
Hey, sorry for the continued trouble. Can you check again? I triggered a manual purge of all the root-level files with `latest` in their names.

**Comment by santiagobasulto** [comment]
I'm having the same issue from Argentina (100 miles away from Uruguay). The issue is that some versions of JQuery Core return 301 with location to the same URL. This does **NOT** happen while VPNing through, for example, the US. Seems to be a local (South America thing).

Examples:

```
$ curl -I https://code.jquery.com/jquery-1.11.0.min.js
HTTP/2 301
location: https://code.jquery.com/jquery-1.11.0.min.js. # This causes the infinite loop
```

```
$ curl -I https://code.jquery.com/jquery-1.11.0.min.js
HTTP/2 301
location: https://code.jquery.com/jquery-1.11.0.min.js. # This causes the infinite loop

$ curl -I https://code.jquery.com/jquery-1.11.3.min.js. # this version works
HTTP/2 200
```

**Comment by muylomas** [comment]
@mgol the issue has been solved

**Comment by Krinkle** [comment]
@santiagobasulto Yikes, that's not good. Those URLs have definitely been purged however, so this is not a caching issue in that case but likely a new ocurrance of the issue with yet additional undocumented CDN routes. We're in the process of changing our strategy, but in the mean time please check https://github.com/jquery/codeorigin.jquery.com/issues/67#issuecomment-751293087 and respond there with additional information so that we can extend our current workaround.
